# Generated by Django 6.0.4 on 2026-05-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContextStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=50)),
                ('context_id', models.CharField(max_length=300, unique=True)),
                ('version', models.IntegerField(default=1)),
                ('payload', models.JSONField()),
                ('stored_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['scope'], name='app_context_scope_8f79a5_idx'), models.Index(fields=['context_id'], name='app_context_context_72f6ae_idx')],
            },
        ),
    ]
